ballegro/urls.py
from django.conf.urls import url
from . import views


app_name='ballegro'
urlpatterns = [
    url(r'^$', views.root, name='root'),
    url(r'^team_show/(?P<team_name>.+)',
        views.team_show, name='team_show'),
    url(r'^offers/(?P<team_name>.+)/(?P<clothes>.+)',
        views.offers, name='offers'),
    url(r'^all_teams$', views.all_teams, name='all_teams'),
    url(r'^search_team/(?P<team_name>\w+)', views.search_team, name='search_team'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('ballegro.urls')),
]

ballegro/models.py
from django.db import models


class League(models.Model):

    name = models.TextField()

    def __str__(self):
        return self.name


class Team(models.Model):

    name = models.TextField()
    image = models.TextField()
    league = models.ForeignKey(League, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Clothes(models.Model):

    url_name = models.TextField(primary_key=True)
    name = models.TextField()
    category = models.TextField(blank=True, null=True)
    add_team_to_phrase = models.BooleanField()

    def __str__(self):
        return self.name

ballegro/views.py
from django.shortcuts import get_object_or_404, render
from urllib.parse import unquote
import json
from django.http import HttpResponse

from .models import Team, League, Clothes
from .api_allegro import get_offers
from .matches import get_upcoming

def root(request):
    all_teams = Team.objects.all()
    upcoming, upcoming_teams = get_upcoming()
    teams = []
    for team in all_teams:
        if team.name in upcoming_teams[:10]:
            teams.append(team)
    return render(request, 'ballegro/root.html',
        {'teams': teams, 'upcoming_matches': upcoming})

def team_show(request, team_name):
    team = get_object_or_404(Team, name=team_name)
    return render(request, 'ballegro/team_show.html', {'team': team})


def offers(request, team_name, clothes):
    team = get_object_or_404(Team, name=team_name)
    clothes_object = get_object_or_404(Clothes, url_name=clothes)
    clothes_phrase = clothes_object.name
    team_phrase = ''

    if (clothes_object.add_team_to_phrase):
        team_phrase = team_name
    results = get_offers(clothes_phrase, team_phrase,
        clothes_object.category)

    if clothes == 'ball':
        league_name = team.league.name
        clothes_phrase += ' ' + league_name
        team_phrase = ''
        results += get_offers(clothes_phrase, team_phrase,
            clothes_object.category)

    return render(request, 'ballegro/offers.html',
        {'team': team, 'results': results})

def all_teams(request):
    leagues = League.objects.all()
    leagues_with_teams = {league: league.team_set.all() for league in leagues}
    return render(request, 'ballegro/all_teams.html', {'leagues_with_teams': leagues_with_teams})

def search_team(request, team_name):
    teams = Team.objects.filter(name__contains=team_name)
    team_names = teams.values_list('name')
    image_names = teams.values_list('image')
    result = []
    for team in zip(team_names, image_names):
        result.append(team)
    print(result)
    return HttpResponse(json.dumps(result), content_type='application/json')

ballegro/templates/ballegro/all_teams.html
{% extends 'ballegro/base.html' %}
{% block content %}
<div class="container main" id="all-teams">
  <div class="row center">
    <h1 class="invite"> Wybierz swój zespół! </h1>
  </div>
  <div class="row jumbotron">
    <aside class="col-md-3" id="leagues">
      <ul class="league-manu">
      {% for league in leagues_with_teams %}
        <li><a class="league-link" data-league="{{league.name}}"> {{ league.name }} </a></li>
      {% endfor %}
      </ul>
    </aside>
    <div class="col-md-9">
      {% for league, teams in leagues_with_teams.items %}
      <div class="league-container" data-league="{{league.name}}">
          <h2> {{ league.name }} </h2>
          <div class="cols" id="tiles">
            {% for team in teams %}
              <div class="col-xs-6 col-md-3" id="team-tile">
                <a href="{% url 'ballegro:team_show' team_name=team %}" class="thumbnail">
                  <img src="{{ team.image }}" class="card-img-top" alt="{{ team.name }}"/>
                </a>
              </div>
            {% endfor %}
          </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

{% endblock content %}

ballegro/templates/ballegro/base.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html lang="pl-PL">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Ballegro</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link href="{% static 'css/main.css' %}" rel="stylesheet" media="screen">
    </head>
    <body>
        <header class="navbar navbar-fixed-top navbar-inverse">
            <a href="{% url 'ballegro:root' %}" id="logo">Ballegro</a>
            <span id="breadcrumbs">
              {% block breadcrumb %}
              {% endblock breadcrumb %}
            </span>
            <div class="navbar-right">
              <a href="{% url 'ballegro:all_teams' %}"> All teams </a>
              <div class="searchbar" id="searchbar">
                  <input class="searchbar__input" placeholder="znajdź drużynę"/>
                  <ul class="searchbar__sugestions-list"></ul>
              </div>
            </div>
        </header>
        <div class="row">

        </div>


        {% block content %}
        {% endblock content %}

	      <footer class="footer">
          <nav>
            <small>
              Ballegro created by:
            </small>
            <ul>
              <li><a href="https://github.com/kasztanka">@Madzia</a></li>
              <li><a href="https://github.com/piotermiarer">@Piotr</a></li>
              <li><a href="https://github.com/mrspejn">@Tomek</a></li>
              <li><a href="https://github.com/k4ju/">@Kaju</a></li>
            </ul>
          </nav>
        </footer>
        <script src="{% static 'js/bundle.js' %}"></script>
    </body>
</html>

ballegro/templates/ballegro/index.html
{% extends 'ballegro/base.html' %}
{% block content %}

  <div class="jumbotron center" id="upcoming">
    <h2> Ligi </h2>
      {% for league, ts in teams.items %}
        <div class="col-xs-6 col-md-3" id="team-tile">{{ league }}
          {% for team in ts %}
              <p>{{ team }}</p>
          {% endfor %}
        </div>
      {% endfor %}
    </div>
  </div>

{% endblock content %}

ballegro/templates/ballegro/offers.html
{% extends 'ballegro/base.html' %}
{% load staticfiles %}
{% block breadcrumb %}
  >
  <a href="{% url 'ballegro:all_teams' %}">>{{ team.league.name }}</a> >
  <a href="{% url 'ballegro:team_show' team_name=team.name %}" >>{{ team.name }}</a>
{% endblock breadcrumb %}
{% block content %}
<div class="container main" id="offers">
    <div class="center">
        {% if results %}
        <ul class="offers-list">
            {% for r in results %}
            <li class="offers-list__element">
                <a href="{{ r.url }}" class="offer thumbnail">
                    <div class="offer__details">
                        <h4 class="offer__title">{{r.name}}</h4>
                        <span class="offer__price">{{ r.prices.buyNow.amount}}{{ r.prices.buyNow.currency}}</span>
                    </div>
                    <img class="offer_image" src="{{ r.images.0.url }}" alt="{{r.name}}"/>
                </a>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <div class="no-offers">
            <h3 class="no-offers__info">Nothing to see here</h3>
            <img class="no-offers__image" src="{% static 'images/benched.svg' %}" />
        </div>
        {% endif %}
    </div>
</div>
{% endblock content %}

ballegro/templates/ballegro/root.html
{% extends 'ballegro/base.html' %}
{% block content %}
<div class="container main" id="root">
      <h2 class="invite"> Skompletuj swój ubiór! </h2>
      <div class="jumbotron center">
        <h2> Nadchodzące mecze </h2>
        <ul class="upcoming">
          {% for match in upcoming_matches.fixtures|slice:":5" %}
            <li class="upcoming__single">
              <span class="upcoming__left">{{ match.homeTeamName }}</span> <span class="upcoming__separator">:</span> <span>{{ match.awayTeamName }}</span>
            </li>
          {% endfor %}
        </ul>
      </div>
      <br/>
      <div class="container">
        <div class="cols" id="tiles">
          {% for team in teams %}
            <div class="col-xs-6 col-md-3" id="team-tile">
              <a href="{% url 'ballegro:team_show' team_name=team %}" class="thumbnail">
                <img src="{{ team.image }}" class="card-img-top" alt="{{ team.name }}"/>
              </a>
            </div>
          {% endfor %}
        </div>
      </div>
  </div>

{% endblock content %}

ballegro/templates/ballegro/search.html
{% extends 'ballegro/base.html' %}
{% block content %}
    {% for r in results %}
    <a href="{{ r.url }}"><img src="{{ r.images.0.url }}"/></a>
    <div>name: {{ r.name }}, price: {{ r.prices.buyNow.amount}}{{ r.prices.buyNow.currency}}</div>
    {% endfor %}
{% endblock content %}

ballegro/templates/ballegro/team_show.html
{% extends 'ballegro/base.html' %}

{% load staticfiles %}
{% block content %}
    <div class="container main" id="team-show" >
        <div class="banner">
            <img class="banner__emblem" src="/{{team.image}}" alt="{{ team.name }}"/>
            <h3 class="banner__heading">{{team.name}}</h3>
        </div>
        <div class="figures">
            <img class="svg-injection" src="{% static 'images/player.svg' %}" />
            <img class="svg-injection" src="{% static 'images/fan.svg' %}" />
        </div>
    </div>
{% endblock content %}